Nexus.OAuth.Web/Controllers/ApplicationsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Nexus.OAuth.Web.Controllers;
public class ApplicationsController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Nexus.OAuth.Web/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Nexus.OAuth.Web.Controllers.Base;
using Nexus.OAuth.Web.Models.Enums;

namespace Nexus.OAuth.Web.Controllers;

public class AuthenticationController : BaseController
{
    public AuthenticationController(IConfiguration config)
        : base(config)
    { }

    public IActionResult Index(string? after)
    {
        after ??= DefaultRedirect;
        if (XssValidation(ref after))
            return XssError();

        ViewBag.RedirectTo = after;
        ViewBag.hCaptchaKey = hCaptchaKey;
        return View();
    }
    public IActionResult Authorize(string client_id, string? state, string? scopes)
    {
        if (XssValidation(ref client_id) ||
            XssValidation(ref scopes) ||
            XssValidation(ref state))
            return XssError();

        Scope[] scopeArray = new[] { Scope.User };

        if (!string.IsNullOrEmpty(scopes))
        {
            bool isValid = GetScopes(out scopeArray, scopes);

            if (!isValid)
            {
                return BadRequest("Verify scopes");
            }
        }

        ViewBag.ClientId = client_id ?? string.Empty;
        ViewBag.Scopes = scopes ?? "user";
        ViewBag.State = state ?? string.Empty;
        return View();
    }
    public IActionResult Redirect()
        => View();

    [NonAction]
    private static bool GetScopes(out Scope[] scopes, string str)
    {
        string[] scopesStrings = str.Split(',');
        scopes = Array.Empty<Scope>();

        List<Scope> scopesList = new();
        foreach (string strScope in scopesStrings)
        {
            bool isValid = Enum.TryParse(strScope, true, out Scope scope);

            if (!isValid ||
                scopesList.Contains(scope))
                return false;

            scopesList.Add(scope);
        }

        scopes = scopesList.ToArray();
        return true;
    }
}

Nexus.OAuth.Web/Views/Shared/Tea.cshtml
<svg class="tea" width="74" height="96" viewbox="0 0 37 48" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M27.0819 17H3.02508C1.91076 17 1.01376 17.9059 1.0485 19.0197C1.15761 22.5177 1.49703 29.7374 2.5 34C4.07125 40.6778 7.18553 44.8868 8.44856 46.3845C8.79051 46.79 9.29799 47 9.82843 47H20.0218C20.639 47 21.2193 46.7159 21.5659 46.2052C22.6765 44.5687 25.2312 40.4282 27.5 34C28.9757 29.8188 29.084 22.4043 29.0441 18.9156C29.0319 17.8436 28.1539 17 27.0819 17Z" stroke="var(--secondary)" stroke-width="2"></path>
    <path d="M29 23.5C29 23.5 34.5 20.5 35.5 25.4999C36.0986 28.4926 34.2033 31.5383 32 32.8713C29.4555 34.4108 28 34 28 34" stroke="var(--secondary)" stroke-width="2"></path>
    <path id="teabag" fill="var(--secondary)" fill-rule="evenodd" clip-rule="evenodd" d="M16 25V17H14V25H12C10.3431 25 9 26.3431 9 28V34C9 35.6569 10.3431 37 12 37H18C19.6569 37 21 35.6569 21 34V28C21 26.3431 19.6569 25 18 25H16ZM11 28C11 27.4477 11.4477 27 12 27H18C18.5523 27 19 27.4477 19 28V34C19 34.5523 18.5523 35 18 35H12C11.4477 35 11 34.5523 11 34V28Z"></path>
    <path id="steamL" d="M17 1C17 1 17 4.5 14 6.5C11 8.5 11 12 11 12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" stroke="var(--secondary)"></path>
    <path id="steamR" d="M21 6C21 6 21 8.22727 19 9.5C17 10.7727 17 13 17 13" stroke="var(--secondary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>

Nexus.OAuth.Web/Views/Shared/Terminal.cshtml
<script src="~/js/Views/Auxiliary/terminal.js"></script>
<link rel="stylesheet" href="~/css/Views/Auxiliary/terminal.css" asp-append-version="true" />

<!-- Criamos um elemento com a classe 'terminal' -->
<div class="terminal" data-redirect="@(ViewBag.RedirectTo ?? string.Empty)">
    <!-- Aqui serão exibidas as mensagens do terminal -->
    <div id="output" class="output"></div>

    <!-- Aqui é onde o usuário irá digitar as entradas -->
    <div class="trm-input">
        <input type="text" id="input" />
        <button type="button"> Enviar </button>
    </div>
</div>

Nexus.OAuth.Web/Views/Shared/_Empty.cshtml
@using System.Threading;
<!DOCTYPE html>
<html lang="@Thread.CurrentThread.CurrentUICulture.ToString()" class="no-js">
<head>
    <meta charset="utf-8" />
    <meta name="HandheldFriendly" content="true" />
    <meta name="MobileOptimized" content="320" />
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, width=device-width, user-scalable=no" />
    <title>@ViewData["Title"] - Nexus</title>
    @await Html.PartialAsync("_ViewImports")
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true" />
</head>
<body class="is-boxed has-animations">
    <main class="body-wrap boxed-container content">
        @RenderBody()

        <section class="content footer">
            <img src="~/img/wave-inverted.svg">
            <div class="content-divided">
                <div class="content left background">
                    <img src="~/img/blob-wave.png">
                </div>
                <div class="content right slide">
                    <h1>Juan Douglas</h1>
                    <p>A <a href="~/Home/Index">Nexus Company</a> tem como objetivo trazer qualidade, seguran&ccedil;a e efici&ecirc;ncia em todos os seus softwares, assim dando a melhor experi&ecirc;ncia aos seus usu&aacute;rios.</p>
                </div>
            </div>
        </section>

        <footer>
            <section class="singup" id="singup">
                <div class="text">
                    <h3>Não é membro da Nexus ?</h3>
                    <p class="text-sm mb-0">
                        Cadastra-se e trabalhe com quem sabe fazer a diferen&ccedil;a.
                    </p>
                </div>
                <div class="buttons">
                    <button type="button" class="button button-primary"
                            onclick="redirectAndBack('/Account/Register');">
                        Cadastro
                    </button>
                </div>
            </section>

            <section class="site-footer">
                <div class="container">
                    <div class="site-footer-inner">
                        <div class="brand footer-brand">
                        </div>
                        <ul class="footer-links list-reset">
                            <li>
                                <a href="~/Home/Index">Inicio</a>
                            </li>
                            <li>
                                <a href="~/Home/Contact">Contato</a>
                            </li>
                            <li>
                                <a href="~/Home/Privacy">Privacidade</a>
                            </li>
                            <li>
                                <a href="https://wa.me/5561992503344?text=Hello%2C+I%27m+need+support+can+you+help+me%3F%21">Equipe</a>
                            </li>
                        </ul>
                        <ul class="footer-social-links list-reset">
                            <li>
                                <a href="https://www.linkedin.com/company/nexuscompany">
                                    <i class="fa fa-lg fa-brands fa-linkedin"> </i>
                                    <span class="screen-reader-text">Linkedin</span>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/TheNexusCompany">
                                    <i class="fa fa-lg fa-brands fa-twitter"> </i>
                                    <span class="screen-reader-text">Twitter</span>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/company.nexus/">
                                    <i class="fa fa-lg fa-brands fa-instagram"></i>
                                    <span class="screen-reader-text">Instagram</span>
                                </a>
                            </li>
                            <li>
                                <a href="https://wa.me/5561992606441?text=Ol%C3%A1%2C%20pode%20me%20ajudar?">
                                    <i class="fa fa-lg fa-brands fa-whatsapp"></i>
                                    <span class="screen-reader-text">Whatsapp</span>
                                </a>
                            </li>
                        </ul>
                        <div class="footer-copyright">© @DateTime.UtcNow.Year Nexus Company, todos os direitos reservados.</div>
                    </div>
                </div>
            </section>
        </footer>
    </main>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Modals", required: false)
    @await Html.PartialAsync("_RedirectModal")
</body>

</html>

Nexus.OAuth.Web/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="@Thread.CurrentThread.CurrentUICulture.Name">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#096e54" />
    <title>@ViewData["Title"] - Nexus</title>
    @await Html.PartialAsync("_ViewImports")
</head>
<body>
    <div class="content">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nexus Company</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>

                        <ul class="navbar" id="loginPanel">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Index">Login</a>
                            </li>
                        </ul>

                        <ul class="navbar-nav user-panel invisible" id="userPanel">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="/img/crystal_contour.svg" />
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item disabled">Você está logado como: <strong id="shortName"> Juan Douglas</strong></a></li>
                                    <li><a class="dropdown-item" href="~/Account/Profile">Meu Perfil</a></li>
                                    <li><a class="dropdown-item danger" onclick="logout()">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; @DateTime.UtcNow.Year - Nexus Company - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
            </div>
        </footer>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Modals", required: false)
    @await Html.PartialAsync("../Account/ConfirmationModal")
    @await Html.PartialAsync("_RedirectModal")
</body>
</html>

Nexus.OAuth.Web/Views/Shared/_Loader.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="visually-hidden" id="loader">
    <!-- Loader -->
    <div id="loading" class="blobs" style="margin-top: 29%;margin-bottom: 0;">
        <div class="blob-center"></div>
        <div class="blob"></div>
        <div class="blob"></div>
        <div class="blob"></div>
        <div class="blob"></div>
        <div class="blob"></div>
        <div class="blob"></div>
    </div>

    <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
        <defs>
            <filter id="goo">
                <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
                <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7"
                               result="goo" />
                <feBlend in="SourceGraphic" in2="goo" />
            </filter>
        </defs>
    </svg>
</div>

Nexus.OAuth.Web/Views/Shared/_RedirectModal.cshtml
<div class="modal modal-full" id="redirectModal" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-dialog-full" role="document">
       <div class="modal-content">
            <iframe src="~/Authentication/Redirect" title="description"
                style="min-width: 100%;min-height: 100%;"></iframe>
       </div>
    </div>
</div>